name: Forward Commits to GitLab

on:
  push:
    branches:
      - main
      - dev

jobs:
  forward-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "github@example.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch Original Author Information
        run: |
          git log -1 --pretty=format:"%an <%ae>" -r HEAD > author_info.txt

      - name: Push to GitLab
        run: |
          # Set your GitLab repository URL
          gitlab_repo_url="https://rendu-git.etna-alternance.net/module-9251/activity-50408/group-996424.git"

          # Push to GitLab repository while preserving the original author's information
          git remote add gitlab $gitlab_repo_url
          GIT_COMMITTER_NAME="$(cat author_info.txt | cut -d '<' -f 1)" GIT_COMMITTER_EMAIL="$(cat author_info.txt | cut -d '<' -f 2 | cut -d '>' -f 1)" git push -u gitlab HEAD:main

          # Optionally, remove the GitLab remote to prevent clutter
          git remote remove gitlab

        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }} 
